 INSERT INTO provinces (name) VALUES ('Buenos Aires');
 INSERT INTO provinces (name) VALUES ('Chaco');
 INSERT INTO provinces (name) VALUES ('Cordoba');
 INSERT INTO provinces (name) VALUES ('La Pampa');
 INSERT INTO provinces (name) VALUES ('Chubut');
 INSERT INTO provinces (name) VALUES ('Jujuy');
 INSERT INTO provinces (name) VALUES ('Salta');
 INSERT INTO provinces (name) VALUES ('Tucuman');
 INSERT INTO provinces (name) VALUES ('Formosa');
 INSERT INTO provinces (name) VALUES ('Catamarca');
 INSERT INTO provinces (name) VALUES ('Santiago del Estero');
 INSERT INTO provinces (name) VALUES ('Corrientes');
 INSERT INTO provinces (name) VALUES ('Mendoza');
 INSERT INTO provinces (name) VALUES ('Entre Rios');
 INSERT INTO provinces (name) VALUES ('Santa Fe');
 INSERT INTO provinces (name) VALUES ('Misiones');
 INSERT INTO provinces (name) VALUES ('Rio Negro');
 INSERT INTO provinces (name) VALUES ('San Juan');
 INSERT INTO provinces (name) VALUES ('San Luis');
 INSERT INTO provinces (name) VALUES ('Santa Cruz');
 INSERT INTO provinces (name) VALUES ('Neuquen');
 INSERT INTO provinces (name) VALUES ('Tierra del Fuego');
 INSERT INTO provinces (name) VALUES ('La Rioja');

 INSERT INTO admins (email,password) VALUES ('admin@admin.com','1234');
 INSERT INTO guards (name, "lastName", cuil, email, password, street, number,location,"coordinateLatitude","coordinateLength") VALUES ('Paula','Quiriti',27373892942,'pauquiriti@hotmail.com','12345', 'Valencia',5888,'Mar del Plata', 41.40 , 21.17);
 INSERT INTO guards (name, "lastName", cuil, email, password, street, number,location,"coordinateLatitude","coordinateLength") VALUES ('Paul','Jones',2037300942,'paul@hotmail.com','99', 'Tierra del Fuego',1999,'Santa Clara ', 45.25 , 2.17);

 INSERT INTO companies (cuit, "legalName", "legalAdress", "contractStartDate","contractEndDate") VALUES (12131311,'la empresa','domicilio 123','2022-01-01','2022-12-01');
 INSERT INTO branches (name, street,number,location,"coordinateLatitude","coordinateLength","companyId") VALUES ('la sucursal','calle',111,'rio cuarto',55.25 , 22.17,1);
